baseURL = 'https://okabe-junya.github.io'
languageCode = 'ja'
defaultContentLanguage = 'ja'
theme = 'hugo-coder'
title = 'okabe-junya.github.io'
publishDir = 'docs'
canonifyurls = true

[params]
author = 'Junya Okabe'
colorScheme = 'auto'
commit = 'https://github.com/Okabe-Junya/Okabe-Junya.github.io/tree'
description = "Junya Okabe's personal website"
info = ['Student majoring in computer science']
keywords = "blog, personal, website, personal website, personal blog, personal blog website, Computer Science"
since = '2022'

# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/Okabe-Junya/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 2
url = "https://twitter.com/Junya_Tsukuba/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 3
url = "https://www.linkedin.com/in/junya-okabe/"


[languages.ja]

[[languages.ja.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.ja.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.ja.menu.main]]
name = "Contact me"
weight = 3
url = "contact/"